services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: mysql_db  # Add this line
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  default:
    name: my_network
    driver: bridge