spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/restaurante?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
# Configuração do Flyway (opcional)
flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate # Opções: none, validate, update, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false # Desativa cache em desenvolvimento
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
      exclude: static/**,public/**
      poll-interval: 2s
      quiet-period: 1s

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE # Logs detalhados do Hibernate

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json