-- Generated by the database client.
CREATE TABLE usuarios(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    password varchar(255),
    role varchar(255),
    username varchar(255) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX ukm2dvbwfge291euvmk6vkkocao ON usuarios USING btree ("username");