-- Generated by the database client.
CREATE TABLE pedidos(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    observacao varchar(255),
    quantidade integer NOT NULL,
    comanda_id bigint NOT NULL,
    item_id bigint NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fkt39xl9h0m4akhi3jvki0e94bv FOREIGN key(comanda_id) REFERENCES comandas(id),
    CONSTRAINT fktcydoj9tljthvdd2s385t5apc FOREIGN key(item_id) REFERENCES itens(id)
);