-- Generated by the database client.
CREATE TABLE comandas(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    numero_mesa integer NOT NULL,
    preco_total double precision NOT NULL,
    status varchar(255) NOT NULL,
    PRIMARY KEY(id)
);